"use client";
import { usePathname } from "next/navigation";

import "./globals.css";
import { Providers } from "./providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SidebarWithHeader from "@/components/sidebar";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isAuthPath =
    pathname.startsWith("/auth") ||
    pathname.startsWith("/auth/login") ||
    pathname.startsWith("/auth/forgotPassword") ||
    pathname.startsWith("/auth/register");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {isAuthPath ? (
            children
          ) : (
            <SidebarWithHeader>{children}</SidebarWithHeader>
          )}
        </Providers>
      </body>
    </html>
  );
}
